options:
  extra_sans:
    type: string
    default: ""
    description: |
      A space-separated list of additional Subject Alternative Names (SAN) entries
      to include in the x509 certificate created for the load balancers.
  proxy_read_timeout:
    type: int
    default: 600
    description: The timeout in seconds for reading a response from proxy server.
  loadbalancer-ips:
    type: string
    default: ""
    description: |
      A space-separated list of IP addresses of load balancers in front of the control plane.
      A common use case for this is having virtual IP addresses floated in front of the
      kubeapi-load-balancer charm. The workers will evenly distribute the load by alternating
      between the IP addresses in this list. For example, if you have 2 IPs and 4 workers,
      each IP will be used by 2 workers.
  ha-cluster-dns:
    type: string
    default: ""
    description: |
      This option specifies the DNS entry to be used in conjunction with the HA Cluster 
      subordinate charm. This option is mutually exclusive with the `ha-cluster-vip`
      option.
  ha-cluster-vip:
    type: string
    default: ""
    description: |
      A space-separated list of virtual IPs that the charm can utilize in conjunction with the
      HA Cluster subordinate charm. This option is mutually exclusive with the `ha-cluster-dns`
      option.
