groups:
  - name: nginx_endpoint_health
    rules:
      - alert: NginxEndpointUnhealthy
        expr: nginx_up{juju_charm!=".*"} != 1
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Nginx endpoint is unhealthy (instance {{ $labels.instance }})
          description: The Nginx endpoint is not in the expected healthy state.
  - name: prometheus_target_missing
    rules:
    - alert: PrometheusTargetMissing
      expr: up{juju_charm!=".*"} == 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Prometheus target missing (instance {{ $labels.instance }})
        description: "Nginx exporter target has disappeared. An exporter might be crashed.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
